# Generated by Django 2.2.13 on 2020-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200715_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='package',
            field=models.CharField(choices=[('website', 'Website'), ('app', 'App Development'), ('graphic', 'Graphics Design')], default='SOME STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='plan',
            field=models.CharField(choices=[('gold', 'Gold'), ('diamond', 'Diamond'), ('platinum', 'Platinum')], default='SOME STRING', max_length=20),
        ),
    ]
