# Generated by Django 2.2.13 on 2020-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200716_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='package',
            field=models.CharField(default='package', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='plan',
            field=models.CharField(default='plan', max_length=20),
        ),
    ]
