# Generated by Django 2.2.13 on 2020-07-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
