# Generated by Django 3.0.8 on 2020-07-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200711_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='video',
        ),
    ]
