# Generated by Django 3.0.8 on 2020-07-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
