# Generated by Django 2.2.13 on 2020-07-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='body',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
