# Generated by Django 2.2.13 on 2020-07-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
